### ISSUE TITLE
Page Goes Blank when Deleting Corner Radius

### ISSUE THREAD

**Issue by leacho73** [bruceborrett/easy-enclosure#1]
Hi,

I've noticed if you clear the 'Corner Radius' field - then the page just displays white and needs a refresh, loosing your changes.

Cheers
Leacho

**Comment by bruceborrett** [comment]
Yes that is annoying, I will get that sorted.

**Comment by bruceborrett** [comment]
This is solved by df194d804398b4e817684122ca085122dccdd198.
