### ISSUE TITLE
Lid insert is always at the outermost edge irrelevant of thickness. 

### ISSUE THREAD

**Issue by radiochild666** [bruceborrett/easy-enclosure#11]
Not sure if this is in the right place but I printed an enclosure with a 2mm insert and it wouldn't fit. I reduced the insert thickness and printed just the lid and it also wouldn't fit. I realised the insert thickness starts from the same distance from the edge, not centred on the groove. Is it possible to add this as an option? My apologies if this is out of line or not appropriate.

**Comment by bruceborrett** [comment]
This is very helpful feedback, thank you,

I am planning to make the clearance on each side of the insert configurable, which should help to solve this type of issue.

I will try and implement this in the next few days or so.

**Comment by radiochild666** [comment]
If you would like me to print for testing just say so, happy to help.

**Comment by bruceborrett** [comment]
This is resolved by 606894c774b7d4a4c12293b1f463f85d0bbdc64b

@radiochild666 please test and let me know

**Comment by radiochild666** [comment]
@bruceborrett Yes, it does. Thank you!
