### ISSUE TITLE
PCB mount holes bug

### ISSUE THREAD

**Issue by Solarbytes** [bruceborrett/easy-enclosure#13]
Great idea and many thanks for making it available on Github!!!

NEVER MIND I tabbed out of the field and suddenly the position for each mount point was editable. Just a bit confusing but it seems to work fine.

When I tried the online version of the tool, I changed the number of PCB holes to 8 and only one hole was displayed in the center of the enclosure. Changing the number back to 4 had no effect.

**Comment by bruceborrett** [comment]
@Solarbytes I have made some improvements to this, please test and let me know if the issues you were experiencing are now resolved.

**Comment by bruceborrett** [comment]
Closing this for now, please re-open if issue persists.
