### ISSUE TITLE
Rectangles on Left and Righ wall not changing in width

### ISSUE THREAD

**Issue by BigJoeFour** [bruceborrett/easy-enclosure#15]
When adding rectangles to the left and righ wall then the width can't be changed. On the front and back wall it works fine.

**Comment by bruceborrett** [comment]
This should be resolved by https://github.com/bruceborrett/easy-enclosure/commit/a19454b4ff4f1119f194d7750b2138d652e69f8f and https://github.com/bruceborrett/easy-enclosure/commit/9a9d3205ab56f02491a4519439bb5943408530ce.

@BigJoeFour please can you test and let me know.
