### ISSUE TITLE
Transparent cover - which filament?

### ISSUE THREAD

**Issue by ser** [bruceborrett/easy-enclosure#2]
Hello,
I am sorry if I'm abusing issues but are you able to recommend from your experience a filament which would make a proper transparent or semi-transparent cover to see the content of the enclosure?

Thanks!

**Comment by bruceborrett** [comment]
Im afraid I do not have any experience with transparent filament, perhaps someone else will have some advice on this then I can add a note to the readme.

**Comment by bruceborrett** [comment]
I found this great article which hopefully solves this question:

https://www.3dsourced.com/rigid-ink/clear-3d-printer-filament/

**Comment by ser** [comment]
A really nice explanation!

"While it’s impossible to print 100% clear models, printing simple designs with thin walls will certainly help."

Are we able to select how thin is the cover in the app?

**Comment by bruceborrett** [comment]
I have made some updates and it is now also possible to configure the thickness of the lid.
