### ISSUE TITLE
Holes menu has formatting errors

### ISSUE THREAD

**Issue by buccaneer-jak** [bruceborrett/easy-enclosure#21]
The Holes section now doesn't show which values are X or Y and the text box formatting is off.

![Web capture_2-11-2023_11436_bruceborrett github io](https://github.com/bruceborrett/easy-enclosure/assets/42079546/e6eaba44-717e-4e90-bd3c-ec525512010e)

**Comment by bruceborrett** [comment]
:man_facepalming: I accidentally deployed some unfinished work, this is now fixed.
