### ISSUE TITLE
Different hole diameters for lid and base

### ISSUE THREAD

**Issue by michaeltanner70** [bruceborrett/easy-enclosure#25]
Different hole diameters for lid and base would make it possible to use inserts in the base instead of self-tapping screws.

**Comment by Th3M1k3y** [comment]
I was about to request just that too :)

**Comment by bruceborrett** [comment]
Done, enjoy :smiley:

![image](https://github.com/bruceborrett/easy-enclosure/assets/7754368/3244a015-9c3c-4b56-ab95-ed771e82eb42)

Closed by 7764012b2de5e0498abd18e105b40f900d718e09

**Comment by Th3M1k3y** [comment]
Heck yes! Going to print a new box with inserts when I get home! 😍

**Comment by michaeltanner70** [comment]
very cool, thanks 🙏
