### ISSUE TITLE
feature: re-calculate manually

### ISSUE THREAD

**Issue by uepsie** [bruceborrett/easy-enclosure#9]
Cool project!
However, it might be helpful to have a setting that disables automatic re-calculation after each change.

**Comment by bruceborrett** [comment]
This has been somewhat improved by c332bd2285981ffcbaf5c281c280e3c22fb37266

However I will be making lots more improvements to the form handling in future

**Comment by bruceborrett** [comment]
Re-rendering and re-calculation has been improved a lot since this was opened. I am going to close this for now, please re-open if you still think this is an issue or still needs further improvement.
